previewproject:
  type: website
  output-dir: docs

website:
  title: "Natalie Alexander"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - STA5073Z_Assignment1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
 