project:
  type: website
  output-dir: docs

website:
  title: "Data Science for Industry"
  navbar:
    search: true
    left:
      - about.qmd
      - STA5073Z_Assignment1.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true