project:
  type: website
  output-dir: docs

website:
  title: "Data Science for Industry"
  navbar:
    left:
        - href: about.qmd
          text: "About"
        - STA5073Z_Assignment1.qmd
        

format:
  html:
    css: styles.css
    toc: true
    theme: journal